### PR TITLE
Fix suggestions CSS and addressing issues

### LINKED ISSUE #64: Fix page title and favicon
The page title and favicon need some love.

### LINKED ISSUE #65: Implement the fine print in home page under suggestions
image

### LINKED ISSUE #68: Implement user profile badge
image

### PR DESCRIPTION
**Pull request by alshakerM**
Fixed suggestions CSS.
Added profile badge

Fixes #68.
Fixed #65
Fixed #64

### CODE REVIEW

**Comment by alshakerM** [comment]
Added margin to suggestions text to match the real IG.

**Comment by alshakerM** [comment]
Added fine print

File: components/FinePrint/FinePrint.js [hunk 1]
```diff
@@ -0,0 +1,32 @@
+import styles from './FinePrint.module.css';
+
+export function FinePrint() {
+  return (
+    <div>
+      <ul className={styles.containerList}>
+        <li className={styles.list}>About</li>
+        <li className={styles.list2}>.</li>
```
Comment (alshakero) [inline components/FinePrint/FinePrint.js:8]: This is what `::after` is exactly for. Check IG's CSS and see how they do it.

File: components/FinePrint/FinePrint.js [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+        <li className={styles.list}>Locations</li>
+        <li className={styles.list2}>.</li>
+        <li className={styles.list}>Top account</li>
+        <li className={styles.list2}>.</li>
+        <li className={styles.list}>Hashtags</li>
+        <li className={styles.list2}>.</li>
+        <li className={styles.list}>Language</li>
+      </ul>
+      <p className={styles.instaText}>© 2021 INSTAGRAM FROM META</p>
```
Comment (alshakero) [inline components/FinePrint/FinePrint.js:29]: This is a bit scary, legally speaking, I'd make it “Instagram Replica by AlshakerM”.

File: components/FinePrint/FinePrint.module.css [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+  margin-top: 25px;
+}
+.list {
+  margin-right: 2.5px;
+  margin-top: 4px;
+}
+.list2 {
+  margin-right: 2.5px;
+  margin-top: 1px;
+}
```
Comment (alshakero) [inline components/FinePrint/FinePrint.module.css:17]: If you use `::after` you won't need this.

File: components/ProfileBadge/ProfileBadge.js [hunk 4]
```diff
@@ -0,0 +1,20 @@
...
+        alt="profile pic"
+        className={styles.profilePic}
+      />
+      <div className={styles.userInfo}>
+        <p className={styles.userName}>
+          <strong>marwan.alshaker</strong>
+        </p>
+        <p className={styles.userRealName}>Marwan Ahmed</p>
+      </div>
+      <button className={styles.switchButton}>Switch</button>
```
Comment (alshakero) [inline components/ProfileBadge/ProfileBadge.js:17]: You can change this to "GitHub" and link to your Github 🍡

**Review by alshakero — CHANGES_REQUESTED** [review]
CLEAN ✨ 

Left a comment on the list. We usually use lists to indicate the type of content. It's important for accessibility to know when a group of items is a list; screen readers will say: "There is a list, first item is this, second item is that". So adding unused list items ruins the purpose of using a list. Other than that, beatuiful.

File: components/FinePrint/FinePrint.js (hunk 1 above)
Comment (alshakerM) [reply components/FinePrint/FinePrint.js:8]: On it.

File: pages/_app.js [hunk 5]
```diff
@@ -1,7 +1,16 @@
-import '../styles/globals.css'
+import Head from 'next/head';
+import '../styles/globals.css';
 
 function MyApp({ Component, pageProps }) {
-  return <Component {...pageProps} />
+  return (
+    <div>
+      <Head>
+        <title>instagram UI</title>
```
Comment (alshakero) [inline pages/_app.js:8]: It's no longer UI. You have a backend now. And the `i` should be capitalized.

Comment (alshakerM) [reply pages/_app.js:8]: Copy that.
Renamed it to Instagram clone

**Comment by alshakerM** [comment]
Deleted some unneeded code and used CSS ::after selector instead.
Renamed the title to clone instead of UI.
Linked my GitHub.

File: pages/_app.js [hunk 6]
```diff
@@ -1,7 +1,16 @@
-import '../styles/globals.css'
+import Head from 'next/head';
+import '../styles/globals.css';
 
 function MyApp({ Component, pageProps }) {
-  return <Component {...pageProps} />
+  return (
+    <div>
+      <Head>
+        <title>instagram clone</title>
```
Comment (alshakero) [inline pages/_app.js:8]: Since this is title, should use title [case](https://en.wikipedia.org/wiki/Title_case).
```suggestion
        <title>Instagram Clone</title>
```

**Review by alshakero — APPROVED** [review]
LGTM!

File: pages/_app.js (hunk 6 above)
Comment (alshakerM) [reply pages/_app.js]: Done

**Review by alshakero — APPROVED** [review]
LGTM
